application: gradient-host
version: 1
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "15m"

handlers:
# Serve images and pdfs as static resources.
- url: /(.+\.(gif|png|jpg|pdf|ico|css|js|fxb|wav|zip))$
  static_files: \1
  upload: .+\.(gif|png|jpg|pdf|ico|css|js|fxb|wav|zip)$
  application_readable: true

# Serve robots.txt
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.py
